# Generated by Django 4.1.3 on 2022-11-12 23:11

import devices.models.device
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('pins', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.BooleanField(default=True)),
                ('device_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_in_tasks', to='devices.deviceitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_tasks', to='devices.item')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_in_tasks', to='devices.devicetask')),
            ],
        ),
        migrations.AddField(
            model_name='devicetask',
            name='status',
            field=models.ForeignKey(blank=True, default=devices.models.device.get_start, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.taskstatus'),
        ),
        migrations.AddField(
            model_name='deviceitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.item'),
        ),
    ]
